Periodic Tests review: Fix 53 54 (#240)
* add missing categories on setup and teardown of test 53

* improve tests 53 and 54

to use less disk space, we were observing the error:

System.IO.IOException: No space left on device 

on the job runs

* add waiter after upload on tests 54, 55, 56

* new category: BigObjects